
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";
import MeditationComponent from "@/components/Meditation";

const Meditate = () => {
  return (
    <div className="min-h-screen flex flex-col">
      <Header />
      
      <main className="flex-1 bloom-container py-8">
        <div className="space-y-8">
          <div className="text-center">
            <h1 className="text-3xl font-bold mb-4 text-gradient">Guided Meditation</h1>
            <p className="text-foreground/80 max-w-2xl mx-auto">
              Experience personalized meditation sessions generated by AI to address your specific emotional needs.
            </p>
          </div>
          
          <MeditationComponent />

        </div>
      </main>
      
      <Footer />
    </div>
  );
};

export default Meditate;
